spring:
  ai:
    openai:
      # DeepSeek Base URL
      base-url: https://api.siliconflow.cn
      # DeepSeek API Key
      api-key: sk-dlecrggdbznuaoefbgdyvzqqyyygjveoeaznorljmhgjunlg


emoSync:
  cloudinary:
    cloud-name: dqkoora74
    api-key: 873477743716381
    api-secret: _CHOBL4cpC1zQeBP4gACWadpAXs

